// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: review/review.proto

package review

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------------- REVIEW PORUKE -----------------
type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rating        int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	TouristId     string                 `protobuf:"bytes,4,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	TourId        string                 `protobuf:"bytes,5,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	VisitDate     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=visit_date,json=visitDate,proto3" json:"visit_date,omitempty"`
	CommentDate   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=comment_date,json=commentDate,proto3" json:"comment_date,omitempty"`
	Images        []string               `protobuf:"bytes,8,rep,name=images,proto3" json:"images,omitempty"`
	TouristName   string                 `protobuf:"bytes,9,opt,name=tourist_name,json=touristName,proto3" json:"tourist_name,omitempty"`
	TouristImage  string                 `protobuf:"bytes,10,opt,name=tourist_image,json=touristImage,proto3" json:"tourist_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_review_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{0}
}

func (x *Review) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Review) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Review) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *Review) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *Review) GetVisitDate() *timestamppb.Timestamp {
	if x != nil {
		return x.VisitDate
	}
	return nil
}

func (x *Review) GetCommentDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CommentDate
	}
	return nil
}

func (x *Review) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Review) GetTouristName() string {
	if x != nil {
		return x.TouristName
	}
	return ""
}

func (x *Review) GetTouristImage() string {
	if x != nil {
		return x.TouristImage
	}
	return ""
}

type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rating        int32                  `protobuf:"varint,1,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	TouristId     string                 `protobuf:"bytes,3,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	TourId        string                 `protobuf:"bytes,4,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	VisitDate     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=visit_date,json=visitDate,proto3" json:"visit_date,omitempty"`
	Images        []string               `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	TouristName   string                 `protobuf:"bytes,7,opt,name=tourist_name,json=touristName,proto3" json:"tourist_name,omitempty"`
	TouristImage  string                 `protobuf:"bytes,8,opt,name=tourist_image,json=touristImage,proto3" json:"tourist_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_review_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CreateReviewRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *CreateReviewRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *CreateReviewRequest) GetVisitDate() *timestamppb.Timestamp {
	if x != nil {
		return x.VisitDate
	}
	return nil
}

func (x *CreateReviewRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateReviewRequest) GetTouristName() string {
	if x != nil {
		return x.TouristName
	}
	return ""
}

func (x *CreateReviewRequest) GetTouristImage() string {
	if x != nil {
		return x.TouristImage
	}
	return ""
}

type GetReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewRequest) Reset() {
	*x = GetReviewRequest{}
	mi := &file_review_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewRequest) ProtoMessage() {}

func (x *GetReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewRequest.ProtoReflect.Descriptor instead.
func (*GetReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{2}
}

func (x *GetReviewRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetReviewsByTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsByTourRequest) Reset() {
	*x = GetReviewsByTourRequest{}
	mi := &file_review_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsByTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsByTourRequest) ProtoMessage() {}

func (x *GetReviewsByTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsByTourRequest.ProtoReflect.Descriptor instead.
func (*GetReviewsByTourRequest) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{3}
}

func (x *GetReviewsByTourRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type GetReviewsByTouristRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsByTouristRequest) Reset() {
	*x = GetReviewsByTouristRequest{}
	mi := &file_review_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsByTouristRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsByTouristRequest) ProtoMessage() {}

func (x *GetReviewsByTouristRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsByTouristRequest.ProtoReflect.Descriptor instead.
func (*GetReviewsByTouristRequest) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{4}
}

func (x *GetReviewsByTouristRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

type UpdateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rating        int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	VisitDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=visit_date,json=visitDate,proto3" json:"visit_date,omitempty"`
	Images        []string               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	TouristName   string                 `protobuf:"bytes,6,opt,name=tourist_name,json=touristName,proto3" json:"tourist_name,omitempty"`
	TouristImage  string                 `protobuf:"bytes,7,opt,name=tourist_image,json=touristImage,proto3" json:"tourist_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReviewRequest) Reset() {
	*x = UpdateReviewRequest{}
	mi := &file_review_review_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReviewRequest) ProtoMessage() {}

func (x *UpdateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReviewRequest.ProtoReflect.Descriptor instead.
func (*UpdateReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateReviewRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *UpdateReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *UpdateReviewRequest) GetVisitDate() *timestamppb.Timestamp {
	if x != nil {
		return x.VisitDate
	}
	return nil
}

func (x *UpdateReviewRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *UpdateReviewRequest) GetTouristName() string {
	if x != nil {
		return x.TouristName
	}
	return ""
}

func (x *UpdateReviewRequest) GetTouristImage() string {
	if x != nil {
		return x.TouristImage
	}
	return ""
}

type DeleteReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewRequest) Reset() {
	*x = DeleteReviewRequest{}
	mi := &file_review_review_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewRequest) ProtoMessage() {}

func (x *DeleteReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewRequest.ProtoReflect.Descriptor instead.
func (*DeleteReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteReviewRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAverageRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAverageRatingRequest) Reset() {
	*x = GetAverageRatingRequest{}
	mi := &file_review_review_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAverageRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAverageRatingRequest) ProtoMessage() {}

func (x *GetAverageRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAverageRatingRequest.ProtoReflect.Descriptor instead.
func (*GetAverageRatingRequest) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{7}
}

func (x *GetAverageRatingRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type ReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewResponse) Reset() {
	*x = ReviewResponse{}
	mi := &file_review_review_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewResponse) ProtoMessage() {}

func (x *ReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewResponse.ProtoReflect.Descriptor instead.
func (*ReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{8}
}

func (x *ReviewResponse) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type GetReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsResponse) Reset() {
	*x = GetReviewsResponse{}
	mi := &file_review_review_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsResponse) ProtoMessage() {}

func (x *GetReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsResponse.ProtoReflect.Descriptor instead.
func (*GetReviewsResponse) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{9}
}

func (x *GetReviewsResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type DeleteReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewResponse) Reset() {
	*x = DeleteReviewResponse{}
	mi := &file_review_review_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewResponse) ProtoMessage() {}

func (x *DeleteReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewResponse.ProtoReflect.Descriptor instead.
func (*DeleteReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteReviewResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetAverageRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AverageRating float64                `protobuf:"fixed64,1,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAverageRatingResponse) Reset() {
	*x = GetAverageRatingResponse{}
	mi := &file_review_review_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAverageRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAverageRatingResponse) ProtoMessage() {}

func (x *GetAverageRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_review_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAverageRatingResponse.ProtoReflect.Descriptor instead.
func (*GetAverageRatingResponse) Descriptor() ([]byte, []int) {
	return file_review_review_proto_rawDescGZIP(), []int{11}
}

func (x *GetAverageRatingResponse) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

var File_review_review_proto protoreflect.FileDescriptor

const file_review_review_proto_rawDesc = "" +
	"\n" +
	"\x13review/review.proto\x12\x06review\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x02\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x04 \x01(\tR\ttouristId\x12\x17\n" +
	"\atour_id\x18\x05 \x01(\tR\x06tourId\x129\n" +
	"\n" +
	"visit_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tvisitDate\x12=\n" +
	"\fcomment_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcommentDate\x12\x16\n" +
	"\x06images\x18\b \x03(\tR\x06images\x12!\n" +
	"\ftourist_name\x18\t \x01(\tR\vtouristName\x12#\n" +
	"\rtourist_image\x18\n" +
	" \x01(\tR\ftouristImage\"\x9a\x02\n" +
	"\x13CreateReviewRequest\x12\x16\n" +
	"\x06rating\x18\x01 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x03 \x01(\tR\ttouristId\x12\x17\n" +
	"\atour_id\x18\x04 \x01(\tR\x06tourId\x129\n" +
	"\n" +
	"visit_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tvisitDate\x12\x16\n" +
	"\x06images\x18\x06 \x03(\tR\x06images\x12!\n" +
	"\ftourist_name\x18\a \x01(\tR\vtouristName\x12#\n" +
	"\rtourist_image\x18\b \x01(\tR\ftouristImage\"\"\n" +
	"\x10GetReviewRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x17GetReviewsByTourRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\";\n" +
	"\x1aGetReviewsByTouristRequest\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\tR\ttouristId\"\xf2\x01\n" +
	"\x13UpdateReviewRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x129\n" +
	"\n" +
	"visit_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tvisitDate\x12\x16\n" +
	"\x06images\x18\x05 \x03(\tR\x06images\x12!\n" +
	"\ftourist_name\x18\x06 \x01(\tR\vtouristName\x12#\n" +
	"\rtourist_image\x18\a \x01(\tR\ftouristImage\"%\n" +
	"\x13DeleteReviewRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x17GetAverageRatingRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\"8\n" +
	"\x0eReviewResponse\x12&\n" +
	"\x06review\x18\x01 \x01(\v2\x0e.review.ReviewR\x06review\">\n" +
	"\x12GetReviewsResponse\x12(\n" +
	"\areviews\x18\x01 \x03(\v2\x0e.review.ReviewR\areviews\"0\n" +
	"\x14DeleteReviewResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"A\n" +
	"\x18GetAverageRatingResponse\x12%\n" +
	"\x0eaverage_rating\x18\x01 \x01(\x01R\raverageRating2\xf2\x05\n" +
	"\rReviewService\x12X\n" +
	"\fCreateReview\x12\x1b.review.CreateReviewRequest\x1a\x16.review.ReviewResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/reviews\x12T\n" +
	"\tGetReview\x12\x18.review.GetReviewRequest\x1a\x16.review.ReviewResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/reviews/{id}\x12q\n" +
	"\x10GetReviewsByTour\x12\x1f.review.GetReviewsByTourRequest\x1a\x1a.review.GetReviewsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/tours/{tour_id}/reviews\x12}\n" +
	"\x13GetReviewsByTourist\x12\".review.GetReviewsByTouristRequest\x1a\x1a.review.GetReviewsResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/tourists/{tourist_id}/reviews\x12]\n" +
	"\fUpdateReview\x12\x1b.review.UpdateReviewRequest\x1a\x16.review.ReviewResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\x1a\r/reviews/{id}\x12`\n" +
	"\fDeleteReview\x12\x1b.review.DeleteReviewRequest\x1a\x1c.review.DeleteReviewResponse\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/reviews/{id}\x12~\n" +
	"\x10GetAverageRating\x12\x1f.review.GetAverageRatingRequest\x1a .review.GetAverageRatingResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/tours/{tour_id}/average-ratingB\x16Z\x14example/proto/reviewb\x06proto3"

var (
	file_review_review_proto_rawDescOnce sync.Once
	file_review_review_proto_rawDescData []byte
)

func file_review_review_proto_rawDescGZIP() []byte {
	file_review_review_proto_rawDescOnce.Do(func() {
		file_review_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_review_proto_rawDesc), len(file_review_review_proto_rawDesc)))
	})
	return file_review_review_proto_rawDescData
}

var file_review_review_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_review_review_proto_goTypes = []any{
	(*Review)(nil),                     // 0: review.Review
	(*CreateReviewRequest)(nil),        // 1: review.CreateReviewRequest
	(*GetReviewRequest)(nil),           // 2: review.GetReviewRequest
	(*GetReviewsByTourRequest)(nil),    // 3: review.GetReviewsByTourRequest
	(*GetReviewsByTouristRequest)(nil), // 4: review.GetReviewsByTouristRequest
	(*UpdateReviewRequest)(nil),        // 5: review.UpdateReviewRequest
	(*DeleteReviewRequest)(nil),        // 6: review.DeleteReviewRequest
	(*GetAverageRatingRequest)(nil),    // 7: review.GetAverageRatingRequest
	(*ReviewResponse)(nil),             // 8: review.ReviewResponse
	(*GetReviewsResponse)(nil),         // 9: review.GetReviewsResponse
	(*DeleteReviewResponse)(nil),       // 10: review.DeleteReviewResponse
	(*GetAverageRatingResponse)(nil),   // 11: review.GetAverageRatingResponse
	(*timestamppb.Timestamp)(nil),      // 12: google.protobuf.Timestamp
}
var file_review_review_proto_depIdxs = []int32{
	12, // 0: review.Review.visit_date:type_name -> google.protobuf.Timestamp
	12, // 1: review.Review.comment_date:type_name -> google.protobuf.Timestamp
	12, // 2: review.CreateReviewRequest.visit_date:type_name -> google.protobuf.Timestamp
	12, // 3: review.UpdateReviewRequest.visit_date:type_name -> google.protobuf.Timestamp
	0,  // 4: review.ReviewResponse.review:type_name -> review.Review
	0,  // 5: review.GetReviewsResponse.reviews:type_name -> review.Review
	1,  // 6: review.ReviewService.CreateReview:input_type -> review.CreateReviewRequest
	2,  // 7: review.ReviewService.GetReview:input_type -> review.GetReviewRequest
	3,  // 8: review.ReviewService.GetReviewsByTour:input_type -> review.GetReviewsByTourRequest
	4,  // 9: review.ReviewService.GetReviewsByTourist:input_type -> review.GetReviewsByTouristRequest
	5,  // 10: review.ReviewService.UpdateReview:input_type -> review.UpdateReviewRequest
	6,  // 11: review.ReviewService.DeleteReview:input_type -> review.DeleteReviewRequest
	7,  // 12: review.ReviewService.GetAverageRating:input_type -> review.GetAverageRatingRequest
	8,  // 13: review.ReviewService.CreateReview:output_type -> review.ReviewResponse
	8,  // 14: review.ReviewService.GetReview:output_type -> review.ReviewResponse
	9,  // 15: review.ReviewService.GetReviewsByTour:output_type -> review.GetReviewsResponse
	9,  // 16: review.ReviewService.GetReviewsByTourist:output_type -> review.GetReviewsResponse
	8,  // 17: review.ReviewService.UpdateReview:output_type -> review.ReviewResponse
	10, // 18: review.ReviewService.DeleteReview:output_type -> review.DeleteReviewResponse
	11, // 19: review.ReviewService.GetAverageRating:output_type -> review.GetAverageRatingResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_review_review_proto_init() }
func file_review_review_proto_init() {
	if File_review_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_review_proto_rawDesc), len(file_review_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_review_review_proto_goTypes,
		DependencyIndexes: file_review_review_proto_depIdxs,
		MessageInfos:      file_review_review_proto_msgTypes,
	}.Build()
	File_review_review_proto = out.File
	file_review_review_proto_goTypes = nil
	file_review_review_proto_depIdxs = nil
}
