syntax = "proto3";

option go_package = "proto/stakeholders";

import "google/api/annotations.proto";

service StakeholdersService {
  // RPC za registraciju korisnika
  rpc RegisterUser (RegistrationRequest) returns (AuthenticationResponse) {
    option (google.api.http) = {
      post: "/users/register"
      body: "*"
    };
  }

  // RPC za login korisnika
  rpc LoginUser (LoginRequest) returns (AuthenticationResponse) {
    option (google.api.http) = {
      post: "/users/login"
      body: "*"
    };
  }

  // RPC za dobijanje svih korisnika
  rpc GetAllUsers (GetAllUsersRequest) returns (GetAllUsersResponse) {
    option (google.api.http) = {
      get: "/admin/users/all"
    };
  }

  // RPC za blokiranje korisnika
  rpc BlockUser (BlockUserRequest) returns (BlockUserResponse) {
    option (google.api.http) = {
      patch: "/admin/users/block/{id}"
      body: "*"
    };
  }

  // RPC za deblokiranje korisnika
  rpc UnblockUser (UnblockUserRequest) returns (UnblockUserResponse) {
    option (google.api.http) = {
      patch: "/admin/users/unblock/{id}"
      body: "*"
    };
  }

  // RPC za dobijanje profila korisnika
  rpc GetUserProfile(GetProfileRequest) returns (UserProfileResponse) {
    option (google.api.http) = {
      get: "/users/profile/{username}"
    };
  }

  // RPC za ažuriranje profila korisnika
  rpc UpdateUserProfile(UpdateProfileRequest) returns (UpdateProfileResponse) {
    option (google.api.http) = {
      put: "/users/profile/{username}"
      body: "*"
    };
  }

  // RPC za upload profilne slike
  rpc UploadProfileImage(UploadProfileImageRequest) returns (UploadProfileImageResponse) {
    option (google.api.http) = {
      post: "/users/profile/upload-image"
      body: "*"
    };
  }

  

}

// ----------------- Poruke -----------------

message RegistrationRequest {
  string username = 1;
  string password = 2;
  string email    = 3;
  string role     = 4;
}

message LoginRequest {
  string username = 1;
  string password = 2;
}

message AuthenticationResponse {
  string accessToken = 1;
}

message GetAllUsersRequest {}

message User {
  string id           = 1;
  string username     = 2;
  string email        = 3;
  string role         = 4;
  bool isBlocked      = 5;
  string firstName    = 6;
  string lastName     = 7;
  string profileImage = 8;
  string biography    = 9;
  string motto        = 10;
}

message GetAllUsersResponse {
  repeated User users = 1;
}

// Blokiranje korisnika
message BlockUserRequest {
  string id = 1; // id korisnika koji se blokira
}
message BlockUserResponse {
  string message = 1;
}

// Deblokiranje korisnika
message UnblockUserRequest {
  string id = 1; // id korisnika koji se deblokira
}
message UnblockUserResponse {
  string message = 1;
}

message GetProfileRequest {
  string username = 1;
}

message UserProfileResponse {
  string id = 1;
  string username = 2;
  string email = 3;
  string role = 4;
  string firstName = 5;
  string lastName = 6;
  string profileImage = 7;
  string biography = 8;
  string motto = 9;
}

message UpdateProfileRequest {
  string username = 1;
  string firstName = 2;
  string lastName = 3;
  string profileImage = 4;
  string biography = 5;
  string motto = 6;
}

message UpdateProfileResponse {
  string message = 1;
  bool success = 2;
}

message UploadProfileImageResponse {
  string username = 1;
  string image_path = 2;
}

// Request za upload profilne slike
  message UploadProfileImageRequest {
    bool success = 1;
    string message = 2;
    string image_url = 3;
  }
