// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: blog/blog-service.proto

package blog

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // iz JWT tokena
	Images        []string               `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`               // putanje do slika
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBlogRequest) Reset() {
	*x = CreateBlogRequest{}
	mi := &file_blog_blog_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogRequest) ProtoMessage() {}

func (x *CreateBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogRequest.ProtoReflect.Descriptor instead.
func (*CreateBlogRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBlogRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBlogRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBlogRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateBlogRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type BlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Images        []string               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlogResponse) Reset() {
	*x = BlogResponse{}
	mi := &file_blog_blog_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogResponse) ProtoMessage() {}

func (x *BlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogResponse.ProtoReflect.Descriptor instead.
func (*BlogResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{1}
}

func (x *BlogResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlogResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BlogResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BlogResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BlogResponse) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *BlogResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetUserBlogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // iz JWT tokena
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBlogsRequest) Reset() {
	*x = GetUserBlogsRequest{}
	mi := &file_blog_blog_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBlogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBlogsRequest) ProtoMessage() {}

func (x *GetUserBlogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBlogsRequest.ProtoReflect.Descriptor instead.
func (*GetUserBlogsRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserBlogsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserBlogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blogs         []*BlogResponse        `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBlogsResponse) Reset() {
	*x = UserBlogsResponse{}
	mi := &file_blog_blog_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBlogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBlogsResponse) ProtoMessage() {}

func (x *UserBlogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBlogsResponse.ProtoReflect.Descriptor instead.
func (*UserBlogsResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{3}
}

func (x *UserBlogsResponse) GetBlogs() []*BlogResponse {
	if x != nil {
		return x.Blogs
	}
	return nil
}

type GetBlogDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogDetailsRequest) Reset() {
	*x = GetBlogDetailsRequest{}
	mi := &file_blog_blog_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogDetailsRequest) ProtoMessage() {}

func (x *GetBlogDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetBlogDetailsRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetBlogDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BlogWithCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blog          *BlogResponse          `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	Comments      []*CommentResponse     `protobuf:"bytes,2,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlogWithCommentsResponse) Reset() {
	*x = BlogWithCommentsResponse{}
	mi := &file_blog_blog_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogWithCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogWithCommentsResponse) ProtoMessage() {}

func (x *BlogWithCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogWithCommentsResponse.ProtoReflect.Descriptor instead.
func (*BlogWithCommentsResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{5}
}

func (x *BlogWithCommentsResponse) GetBlog() *BlogResponse {
	if x != nil {
		return x.Blog
	}
	return nil
}

func (x *BlogWithCommentsResponse) GetComments() []*CommentResponse {
	if x != nil {
		return x.Comments
	}
	return nil
}

// ================== Comment poruke ==================
type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"` // iz path-a
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`             // iz body-ja
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // iz JWT tokena
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_blog_blog_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCommentRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BlogId        string                 `protobuf:"bytes,2,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentResponse) Reset() {
	*x = CommentResponse{}
	mi := &file_blog_blog_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentResponse) ProtoMessage() {}

func (x *CommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentResponse.ProtoReflect.Descriptor instead.
func (*CommentResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{7}
}

func (x *CommentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommentResponse) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *CommentResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CommentResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CommentResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UpdateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // path param
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // body
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_blog_blog_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCommentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ToggleLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"` // iz path-a
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // iz JWT-a (gateway može da upiše ovde)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleLikeRequest) Reset() {
	*x = ToggleLikeRequest{}
	mi := &file_blog_blog_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleLikeRequest) ProtoMessage() {}

func (x *ToggleLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleLikeRequest.ProtoReflect.Descriptor instead.
func (*ToggleLikeRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{9}
}

func (x *ToggleLikeRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *ToggleLikeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ToggleLikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"` // true = sada lajkovano, false = sada unlikovano
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // ukupan broj lajkova nakon akcije
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleLikeResponse) Reset() {
	*x = ToggleLikeResponse{}
	mi := &file_blog_blog_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleLikeResponse) ProtoMessage() {}

func (x *ToggleLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleLikeResponse.ProtoReflect.Descriptor instead.
func (*ToggleLikeResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{10}
}

func (x *ToggleLikeResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *ToggleLikeResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type HasUserLikedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"` // iz path-a
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // iz JWT-a
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasUserLikedRequest) Reset() {
	*x = HasUserLikedRequest{}
	mi := &file_blog_blog_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasUserLikedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasUserLikedRequest) ProtoMessage() {}

func (x *HasUserLikedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasUserLikedRequest.ProtoReflect.Descriptor instead.
func (*HasUserLikedRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{11}
}

func (x *HasUserLikedRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *HasUserLikedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type HasUserLikedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasUserLikedResponse) Reset() {
	*x = HasUserLikedResponse{}
	mi := &file_blog_blog_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasUserLikedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasUserLikedResponse) ProtoMessage() {}

func (x *HasUserLikedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasUserLikedResponse.ProtoReflect.Descriptor instead.
func (*HasUserLikedResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{12}
}

func (x *HasUserLikedResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

type CountLikesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"` // iz path-a
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountLikesRequest) Reset() {
	*x = CountLikesRequest{}
	mi := &file_blog_blog_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountLikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountLikesRequest) ProtoMessage() {}

func (x *CountLikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountLikesRequest.ProtoReflect.Descriptor instead.
func (*CountLikesRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{13}
}

func (x *CountLikesRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

type CountLikesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountLikesResponse) Reset() {
	*x = CountLikesResponse{}
	mi := &file_blog_blog_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountLikesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountLikesResponse) ProtoMessage() {}

func (x *CountLikesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountLikesResponse.ProtoReflect.Descriptor instead.
func (*CountLikesResponse) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{14}
}

func (x *CountLikesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetByFolloweeIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolloweeIds   []string               `protobuf:"bytes,1,rep,name=followee_ids,json=followeeIds,proto3" json:"followee_ids,omitempty"`
	Skip          int32                  `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByFolloweeIdsRequest) Reset() {
	*x = GetByFolloweeIdsRequest{}
	mi := &file_blog_blog_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByFolloweeIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByFolloweeIdsRequest) ProtoMessage() {}

func (x *GetByFolloweeIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_blog_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByFolloweeIdsRequest.ProtoReflect.Descriptor instead.
func (*GetByFolloweeIdsRequest) Descriptor() ([]byte, []int) {
	return file_blog_blog_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetByFolloweeIdsRequest) GetFolloweeIds() []string {
	if x != nil {
		return x.FolloweeIds
	}
	return nil
}

func (x *GetByFolloweeIdsRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *GetByFolloweeIdsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_blog_blog_service_proto protoreflect.FileDescriptor

const file_blog_blog_service_proto_rawDesc = "" +
	"\n" +
	"\x17blog/blog-service.proto\x1a\x1cgoogle/api/annotations.proto\"|\n" +
	"\x11CreateBlogRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06images\x18\x04 \x03(\tR\x06images\"\xa6\x01\n" +
	"\fBlogResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x16\n" +
	"\x06images\x18\x05 \x03(\tR\x06images\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\".\n" +
	"\x13GetUserBlogsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\x11UserBlogsResponse\x12#\n" +
	"\x05blogs\x18\x01 \x03(\v2\r.BlogResponseR\x05blogs\"'\n" +
	"\x15GetBlogDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"k\n" +
	"\x18BlogWithCommentsResponse\x12!\n" +
	"\x04blog\x18\x01 \x01(\v2\r.BlogResponseR\x04blog\x12,\n" +
	"\bcomments\x18\x02 \x03(\v2\x10.CommentResponseR\bcomments\"b\n" +
	"\x14CreateCommentRequest\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\xab\x01\n" +
	"\x0fCommentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ablog_id\x18\x02 \x01(\tR\x06blogId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"@\n" +
	"\x14UpdateCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"E\n" +
	"\x11ToggleLikeRequest\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"@\n" +
	"\x12ToggleLikeResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"G\n" +
	"\x13HasUserLikedRequest\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\",\n" +
	"\x14HasUserLikedResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\",\n" +
	"\x11CountLikesRequest\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\"*\n" +
	"\x12CountLikesResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\"f\n" +
	"\x17GetByFolloweeIdsRequest\x12!\n" +
	"\ffollowee_ids\x18\x01 \x03(\tR\vfolloweeIds\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit2\xd2\x06\n" +
	"\vBlogService\x12N\n" +
	"\n" +
	"CreateBlog\x12\x12.CreateBlogRequest\x1a\r.BlogResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/blogs/create-blog\x12M\n" +
	"\fGetUserBlogs\x12\x14.GetUserBlogsRequest\x1a\x12.UserBlogsResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/blogs/user\x12`\n" +
	"\x0eGetBlogDetails\x12\x16.GetBlogDetailsRequest\x1a\x19.BlogWithCommentsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/blogs/{id}/details\x12^\n" +
	"\rCreateComment\x12\x15.CreateCommentRequest\x1a\x10.CommentResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/blogs/{blog_id}/comments\x12Y\n" +
	"\rUpdateComment\x12\x15.UpdateCommentRequest\x1a\x10.CommentResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/blogs/comments/{id}\x12_\n" +
	"\n" +
	"ToggleLike\x12\x12.ToggleLikeRequest\x1a\x13.ToggleLikeResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/blogs/{blog_id}/likes:toggle\x12^\n" +
	"\fHasUserLiked\x12\x14.HasUserLikedRequest\x1a\x15.HasUserLikedResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/blogs/{blog_id}/likes/me\x12[\n" +
	"\n" +
	"CountLikes\x12\x12.CountLikesRequest\x1a\x13.CountLikesResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/blogs/{blog_id}/likes/count\x12i\n" +
	"\x13GetBlogsByFollowees\x12\x18.GetByFolloweeIdsRequest\x1a\x12.UserBlogsResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/blogs/by-followees:queryB\fZ\n" +
	"proto/blogb\x06proto3"

var (
	file_blog_blog_service_proto_rawDescOnce sync.Once
	file_blog_blog_service_proto_rawDescData []byte
)

func file_blog_blog_service_proto_rawDescGZIP() []byte {
	file_blog_blog_service_proto_rawDescOnce.Do(func() {
		file_blog_blog_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_blog_service_proto_rawDesc), len(file_blog_blog_service_proto_rawDesc)))
	})
	return file_blog_blog_service_proto_rawDescData
}

var file_blog_blog_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_blog_blog_service_proto_goTypes = []any{
	(*CreateBlogRequest)(nil),        // 0: CreateBlogRequest
	(*BlogResponse)(nil),             // 1: BlogResponse
	(*GetUserBlogsRequest)(nil),      // 2: GetUserBlogsRequest
	(*UserBlogsResponse)(nil),        // 3: UserBlogsResponse
	(*GetBlogDetailsRequest)(nil),    // 4: GetBlogDetailsRequest
	(*BlogWithCommentsResponse)(nil), // 5: BlogWithCommentsResponse
	(*CreateCommentRequest)(nil),     // 6: CreateCommentRequest
	(*CommentResponse)(nil),          // 7: CommentResponse
	(*UpdateCommentRequest)(nil),     // 8: UpdateCommentRequest
	(*ToggleLikeRequest)(nil),        // 9: ToggleLikeRequest
	(*ToggleLikeResponse)(nil),       // 10: ToggleLikeResponse
	(*HasUserLikedRequest)(nil),      // 11: HasUserLikedRequest
	(*HasUserLikedResponse)(nil),     // 12: HasUserLikedResponse
	(*CountLikesRequest)(nil),        // 13: CountLikesRequest
	(*CountLikesResponse)(nil),       // 14: CountLikesResponse
	(*GetByFolloweeIdsRequest)(nil),  // 15: GetByFolloweeIdsRequest
}
var file_blog_blog_service_proto_depIdxs = []int32{
	1,  // 0: UserBlogsResponse.blogs:type_name -> BlogResponse
	1,  // 1: BlogWithCommentsResponse.blog:type_name -> BlogResponse
	7,  // 2: BlogWithCommentsResponse.comments:type_name -> CommentResponse
	0,  // 3: BlogService.CreateBlog:input_type -> CreateBlogRequest
	2,  // 4: BlogService.GetUserBlogs:input_type -> GetUserBlogsRequest
	4,  // 5: BlogService.GetBlogDetails:input_type -> GetBlogDetailsRequest
	6,  // 6: BlogService.CreateComment:input_type -> CreateCommentRequest
	8,  // 7: BlogService.UpdateComment:input_type -> UpdateCommentRequest
	9,  // 8: BlogService.ToggleLike:input_type -> ToggleLikeRequest
	11, // 9: BlogService.HasUserLiked:input_type -> HasUserLikedRequest
	13, // 10: BlogService.CountLikes:input_type -> CountLikesRequest
	15, // 11: BlogService.GetBlogsByFollowees:input_type -> GetByFolloweeIdsRequest
	1,  // 12: BlogService.CreateBlog:output_type -> BlogResponse
	3,  // 13: BlogService.GetUserBlogs:output_type -> UserBlogsResponse
	5,  // 14: BlogService.GetBlogDetails:output_type -> BlogWithCommentsResponse
	7,  // 15: BlogService.CreateComment:output_type -> CommentResponse
	7,  // 16: BlogService.UpdateComment:output_type -> CommentResponse
	10, // 17: BlogService.ToggleLike:output_type -> ToggleLikeResponse
	12, // 18: BlogService.HasUserLiked:output_type -> HasUserLikedResponse
	14, // 19: BlogService.CountLikes:output_type -> CountLikesResponse
	3,  // 20: BlogService.GetBlogsByFollowees:output_type -> UserBlogsResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_blog_blog_service_proto_init() }
func file_blog_blog_service_proto_init() {
	if File_blog_blog_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_blog_service_proto_rawDesc), len(file_blog_blog_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_blog_service_proto_goTypes,
		DependencyIndexes: file_blog_blog_service_proto_depIdxs,
		MessageInfos:      file_blog_blog_service_proto_msgTypes,
	}.Build()
	File_blog_blog_service_proto = out.File
	file_blog_blog_service_proto_goTypes = nil
	file_blog_blog_service_proto_depIdxs = nil
}
