syntax = "proto3";

option go_package = "proto/blog";

import "google/api/annotations.proto";

service BlogService {
    rpc CreateBlog (CreateBlogRequest) returns (BlogResponse) {
        option (google.api.http) = {
            post: "/blogs/create-blog"
            body:"*"
        };
    }

//Dohvatanje blogova po userId
    rpc GetUserBlogs (GetUserBlogsRequest) returns (UserBlogsResponse) {
        option (google.api.http) = {
            get: "/blogs/user"
        };
    }

//Dohvatanje bloga po id-u sa komentarima
    rpc GetBlogDetails (GetBlogDetailsRequest) returns (BlogWithCommentsResponse) {
        option (google.api.http) = {
            get: "/blogs/{id}/details"
        };
    }

// Kreiranje komentara
    rpc CreateComment (CreateCommentRequest) returns (CommentResponse) {
        option (google.api.http) = {
            post: "/blogs/{blog_id}/comments"
            body: "*"
        };
    }

}

message CreateBlogRequest {
  string title = 1;
  string description = 2;
  string user_id = 3;          // iz JWT tokena
  repeated string images = 4;  // putanje do slika
}

message BlogResponse {
  string id = 1;
    string title = 2;
    string description = 3;
    string user_id = 4;
    repeated string images = 5;
    string created_at = 6;
}


message GetUserBlogsRequest {
  string user_id = 1;  // iz JWT tokena
}

message UserBlogsResponse {
  repeated BlogResponse blogs = 1;
}

message GetBlogDetailsRequest {
  string id = 1;
}

message BlogWithCommentsResponse {
  BlogResponse blog = 1;
  repeated CommentResponse comments = 2;
}

// ================== Comment poruke ==================
message CreateCommentRequest {
    string blog_id = 1; // iz path-a
    string content = 2; // iz body-ja
    string user_id = 3; // iz JWT tokena
}

message CommentResponse {
    string id = 1;
    string blog_id = 2;
    string user_id = 3;
    string content = 4;
    string created_at = 5;
    string updated_at = 6;
}