// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.1
// source: tours/tours-service.proto

package tours

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ToursService_CreateTour_FullMethodName          = "/ToursService/CreateTour"
	ToursService_GetAuthorTours_FullMethodName      = "/ToursService/GetAuthorTours"
	ToursService_GetTourById_FullMethodName         = "/ToursService/GetTourById"
	ToursService_AddKeyPoint_FullMethodName         = "/ToursService/AddKeyPoint"
	ToursService_UpdateKeyPoint_FullMethodName      = "/ToursService/UpdateKeyPoint"
	ToursService_DeleteKeyPoint_FullMethodName      = "/ToursService/DeleteKeyPoint"
	ToursService_GetPublishedTours_FullMethodName   = "/ToursService/GetPublishedTours"
	ToursService_GetAllTours_FullMethodName         = "/ToursService/GetAllTours"
	ToursService_StartTour_FullMethodName           = "/ToursService/StartTour"
	ToursService_LeaveTour_FullMethodName           = "/ToursService/LeaveTour"
	ToursService_NotifyNearKeyPoint_FullMethodName  = "/ToursService/NotifyNearKeyPoint"
	ToursService_GetActiveTour_FullMethodName       = "/ToursService/GetActiveTour"
	ToursService_HasTourExecution_FullMethodName    = "/ToursService/HasTourExecution"
	ToursService_CheckTourCompletion_FullMethodName = "/ToursService/CheckTourCompletion"
)

// ToursServiceClient is the client API for ToursService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ToursServiceClient interface {
	// Kreiranje nove ture
	CreateTour(ctx context.Context, in *CreateTourRequest, opts ...grpc.CallOption) (*TourResponse, error)
	// Preuzimanje svih tura od autora
	GetAuthorTours(ctx context.Context, in *GetAuthorToursRequest, opts ...grpc.CallOption) (*GetAuthorToursResponse, error)
	// Dobavljanje ture po id
	GetTourById(ctx context.Context, in *GetTourByIdRequest, opts ...grpc.CallOption) (*TourResponse, error)
	// Dodavanje ključne tačke na turu
	AddKeyPoint(ctx context.Context, in *AddKeyPointRequest, opts ...grpc.CallOption) (*KeyPointResponse, error)
	UpdateKeyPoint(ctx context.Context, in *UpdateKeyPointRequest, opts ...grpc.CallOption) (*KeyPointResponse, error)
	DeleteKeyPoint(ctx context.Context, in *DeleteKeyPointRequest, opts ...grpc.CallOption) (*DeleteKeyPointResponse, error)
	// Dobavljanje svih publikovanih tura (za frontend)
	GetPublishedTours(ctx context.Context, in *GetPublishedToursRequest, opts ...grpc.CallOption) (*GetPublishedToursResponse, error)
	GetAllTours(ctx context.Context, in *GetAllToursRequest, opts ...grpc.CallOption) (*GetAllToursResponse, error)
	StartTour(ctx context.Context, in *StartTourRequest, opts ...grpc.CallOption) (*StartTourResponse, error)
	LeaveTour(ctx context.Context, in *LeaveTourRequest, opts ...grpc.CallOption) (*LeaveTourResponse, error)
	// Obaveštavanje backend-a da je korisnik blizu ključne tačke
	NotifyNearKeyPoint(ctx context.Context, in *NotifyNearKeyPointRequest, opts ...grpc.CallOption) (*NotifyNearKeyPointResponse, error)
	// Dobavljanje aktivne ture za datog turistu
	GetActiveTour(ctx context.Context, in *GetActiveTourRequest, opts ...grpc.CallOption) (*GetActiveTourResponse, error)
	HasTourExecution(ctx context.Context, in *HasTourExecutionRequest, opts ...grpc.CallOption) (*HasTourExecutionResponse, error)
	// RPC za proveru završetka ture
	CheckTourCompletion(ctx context.Context, in *CheckTourCompletionRequest, opts ...grpc.CallOption) (*CheckTourCompletionResponse, error)
}

type toursServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToursServiceClient(cc grpc.ClientConnInterface) ToursServiceClient {
	return &toursServiceClient{cc}
}

func (c *toursServiceClient) CreateTour(ctx context.Context, in *CreateTourRequest, opts ...grpc.CallOption) (*TourResponse, error) {
	out := new(TourResponse)
	err := c.cc.Invoke(ctx, ToursService_CreateTour_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) GetAuthorTours(ctx context.Context, in *GetAuthorToursRequest, opts ...grpc.CallOption) (*GetAuthorToursResponse, error) {
	out := new(GetAuthorToursResponse)
	err := c.cc.Invoke(ctx, ToursService_GetAuthorTours_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) GetTourById(ctx context.Context, in *GetTourByIdRequest, opts ...grpc.CallOption) (*TourResponse, error) {
	out := new(TourResponse)
	err := c.cc.Invoke(ctx, ToursService_GetTourById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) AddKeyPoint(ctx context.Context, in *AddKeyPointRequest, opts ...grpc.CallOption) (*KeyPointResponse, error) {
	out := new(KeyPointResponse)
	err := c.cc.Invoke(ctx, ToursService_AddKeyPoint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) UpdateKeyPoint(ctx context.Context, in *UpdateKeyPointRequest, opts ...grpc.CallOption) (*KeyPointResponse, error) {
	out := new(KeyPointResponse)
	err := c.cc.Invoke(ctx, ToursService_UpdateKeyPoint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) DeleteKeyPoint(ctx context.Context, in *DeleteKeyPointRequest, opts ...grpc.CallOption) (*DeleteKeyPointResponse, error) {
	out := new(DeleteKeyPointResponse)
	err := c.cc.Invoke(ctx, ToursService_DeleteKeyPoint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) GetPublishedTours(ctx context.Context, in *GetPublishedToursRequest, opts ...grpc.CallOption) (*GetPublishedToursResponse, error) {
	out := new(GetPublishedToursResponse)
	err := c.cc.Invoke(ctx, ToursService_GetPublishedTours_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) GetAllTours(ctx context.Context, in *GetAllToursRequest, opts ...grpc.CallOption) (*GetAllToursResponse, error) {
	out := new(GetAllToursResponse)
	err := c.cc.Invoke(ctx, ToursService_GetAllTours_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) StartTour(ctx context.Context, in *StartTourRequest, opts ...grpc.CallOption) (*StartTourResponse, error) {
	out := new(StartTourResponse)
	err := c.cc.Invoke(ctx, ToursService_StartTour_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) LeaveTour(ctx context.Context, in *LeaveTourRequest, opts ...grpc.CallOption) (*LeaveTourResponse, error) {
	out := new(LeaveTourResponse)
	err := c.cc.Invoke(ctx, ToursService_LeaveTour_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) NotifyNearKeyPoint(ctx context.Context, in *NotifyNearKeyPointRequest, opts ...grpc.CallOption) (*NotifyNearKeyPointResponse, error) {
	out := new(NotifyNearKeyPointResponse)
	err := c.cc.Invoke(ctx, ToursService_NotifyNearKeyPoint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) GetActiveTour(ctx context.Context, in *GetActiveTourRequest, opts ...grpc.CallOption) (*GetActiveTourResponse, error) {
	out := new(GetActiveTourResponse)
	err := c.cc.Invoke(ctx, ToursService_GetActiveTour_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) HasTourExecution(ctx context.Context, in *HasTourExecutionRequest, opts ...grpc.CallOption) (*HasTourExecutionResponse, error) {
	out := new(HasTourExecutionResponse)
	err := c.cc.Invoke(ctx, ToursService_HasTourExecution_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toursServiceClient) CheckTourCompletion(ctx context.Context, in *CheckTourCompletionRequest, opts ...grpc.CallOption) (*CheckTourCompletionResponse, error) {
	out := new(CheckTourCompletionResponse)
	err := c.cc.Invoke(ctx, ToursService_CheckTourCompletion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToursServiceServer is the server API for ToursService service.
// All implementations must embed UnimplementedToursServiceServer
// for forward compatibility
type ToursServiceServer interface {
	// Kreiranje nove ture
	CreateTour(context.Context, *CreateTourRequest) (*TourResponse, error)
	// Preuzimanje svih tura od autora
	GetAuthorTours(context.Context, *GetAuthorToursRequest) (*GetAuthorToursResponse, error)
	// Dobavljanje ture po id
	GetTourById(context.Context, *GetTourByIdRequest) (*TourResponse, error)
	// Dodavanje ključne tačke na turu
	AddKeyPoint(context.Context, *AddKeyPointRequest) (*KeyPointResponse, error)
	UpdateKeyPoint(context.Context, *UpdateKeyPointRequest) (*KeyPointResponse, error)
	DeleteKeyPoint(context.Context, *DeleteKeyPointRequest) (*DeleteKeyPointResponse, error)
	// Dobavljanje svih publikovanih tura (za frontend)
	GetPublishedTours(context.Context, *GetPublishedToursRequest) (*GetPublishedToursResponse, error)
	GetAllTours(context.Context, *GetAllToursRequest) (*GetAllToursResponse, error)
	StartTour(context.Context, *StartTourRequest) (*StartTourResponse, error)
	LeaveTour(context.Context, *LeaveTourRequest) (*LeaveTourResponse, error)
	// Obaveštavanje backend-a da je korisnik blizu ključne tačke
	NotifyNearKeyPoint(context.Context, *NotifyNearKeyPointRequest) (*NotifyNearKeyPointResponse, error)
	// Dobavljanje aktivne ture za datog turistu
	GetActiveTour(context.Context, *GetActiveTourRequest) (*GetActiveTourResponse, error)
	HasTourExecution(context.Context, *HasTourExecutionRequest) (*HasTourExecutionResponse, error)
	// RPC za proveru završetka ture
	CheckTourCompletion(context.Context, *CheckTourCompletionRequest) (*CheckTourCompletionResponse, error)
	mustEmbedUnimplementedToursServiceServer()
}

// UnimplementedToursServiceServer must be embedded to have forward compatible implementations.
type UnimplementedToursServiceServer struct {
}

func (UnimplementedToursServiceServer) CreateTour(context.Context, *CreateTourRequest) (*TourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTour not implemented")
}
func (UnimplementedToursServiceServer) GetAuthorTours(context.Context, *GetAuthorToursRequest) (*GetAuthorToursResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthorTours not implemented")
}
func (UnimplementedToursServiceServer) GetTourById(context.Context, *GetTourByIdRequest) (*TourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTourById not implemented")
}
func (UnimplementedToursServiceServer) AddKeyPoint(context.Context, *AddKeyPointRequest) (*KeyPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddKeyPoint not implemented")
}
func (UnimplementedToursServiceServer) UpdateKeyPoint(context.Context, *UpdateKeyPointRequest) (*KeyPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKeyPoint not implemented")
}
func (UnimplementedToursServiceServer) DeleteKeyPoint(context.Context, *DeleteKeyPointRequest) (*DeleteKeyPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKeyPoint not implemented")
}
func (UnimplementedToursServiceServer) GetPublishedTours(context.Context, *GetPublishedToursRequest) (*GetPublishedToursResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublishedTours not implemented")
}
func (UnimplementedToursServiceServer) GetAllTours(context.Context, *GetAllToursRequest) (*GetAllToursResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTours not implemented")
}
func (UnimplementedToursServiceServer) StartTour(context.Context, *StartTourRequest) (*StartTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTour not implemented")
}
func (UnimplementedToursServiceServer) LeaveTour(context.Context, *LeaveTourRequest) (*LeaveTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveTour not implemented")
}
func (UnimplementedToursServiceServer) NotifyNearKeyPoint(context.Context, *NotifyNearKeyPointRequest) (*NotifyNearKeyPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyNearKeyPoint not implemented")
}
func (UnimplementedToursServiceServer) GetActiveTour(context.Context, *GetActiveTourRequest) (*GetActiveTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveTour not implemented")
}
func (UnimplementedToursServiceServer) HasTourExecution(context.Context, *HasTourExecutionRequest) (*HasTourExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasTourExecution not implemented")
}
func (UnimplementedToursServiceServer) CheckTourCompletion(context.Context, *CheckTourCompletionRequest) (*CheckTourCompletionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTourCompletion not implemented")
}
func (UnimplementedToursServiceServer) mustEmbedUnimplementedToursServiceServer() {}

// UnsafeToursServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToursServiceServer will
// result in compilation errors.
type UnsafeToursServiceServer interface {
	mustEmbedUnimplementedToursServiceServer()
}

func RegisterToursServiceServer(s grpc.ServiceRegistrar, srv ToursServiceServer) {
	s.RegisterService(&ToursService_ServiceDesc, srv)
}

func _ToursService_CreateTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).CreateTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_CreateTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).CreateTour(ctx, req.(*CreateTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_GetAuthorTours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorToursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).GetAuthorTours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_GetAuthorTours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).GetAuthorTours(ctx, req.(*GetAuthorToursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_GetTourById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTourByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).GetTourById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_GetTourById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).GetTourById(ctx, req.(*GetTourByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_AddKeyPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddKeyPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).AddKeyPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_AddKeyPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).AddKeyPoint(ctx, req.(*AddKeyPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_UpdateKeyPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKeyPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).UpdateKeyPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_UpdateKeyPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).UpdateKeyPoint(ctx, req.(*UpdateKeyPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_DeleteKeyPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeyPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).DeleteKeyPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_DeleteKeyPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).DeleteKeyPoint(ctx, req.(*DeleteKeyPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_GetPublishedTours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublishedToursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).GetPublishedTours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_GetPublishedTours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).GetPublishedTours(ctx, req.(*GetPublishedToursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_GetAllTours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllToursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).GetAllTours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_GetAllTours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).GetAllTours(ctx, req.(*GetAllToursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_StartTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).StartTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_StartTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).StartTour(ctx, req.(*StartTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_LeaveTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).LeaveTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_LeaveTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).LeaveTour(ctx, req.(*LeaveTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_NotifyNearKeyPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyNearKeyPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).NotifyNearKeyPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_NotifyNearKeyPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).NotifyNearKeyPoint(ctx, req.(*NotifyNearKeyPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_GetActiveTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).GetActiveTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_GetActiveTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).GetActiveTour(ctx, req.(*GetActiveTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_HasTourExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasTourExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).HasTourExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_HasTourExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).HasTourExecution(ctx, req.(*HasTourExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToursService_CheckTourCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTourCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToursServiceServer).CheckTourCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToursService_CheckTourCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToursServiceServer).CheckTourCompletion(ctx, req.(*CheckTourCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToursService_ServiceDesc is the grpc.ServiceDesc for ToursService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToursService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ToursService",
	HandlerType: (*ToursServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTour",
			Handler:    _ToursService_CreateTour_Handler,
		},
		{
			MethodName: "GetAuthorTours",
			Handler:    _ToursService_GetAuthorTours_Handler,
		},
		{
			MethodName: "GetTourById",
			Handler:    _ToursService_GetTourById_Handler,
		},
		{
			MethodName: "AddKeyPoint",
			Handler:    _ToursService_AddKeyPoint_Handler,
		},
		{
			MethodName: "UpdateKeyPoint",
			Handler:    _ToursService_UpdateKeyPoint_Handler,
		},
		{
			MethodName: "DeleteKeyPoint",
			Handler:    _ToursService_DeleteKeyPoint_Handler,
		},
		{
			MethodName: "GetPublishedTours",
			Handler:    _ToursService_GetPublishedTours_Handler,
		},
		{
			MethodName: "GetAllTours",
			Handler:    _ToursService_GetAllTours_Handler,
		},
		{
			MethodName: "StartTour",
			Handler:    _ToursService_StartTour_Handler,
		},
		{
			MethodName: "LeaveTour",
			Handler:    _ToursService_LeaveTour_Handler,
		},
		{
			MethodName: "NotifyNearKeyPoint",
			Handler:    _ToursService_NotifyNearKeyPoint_Handler,
		},
		{
			MethodName: "GetActiveTour",
			Handler:    _ToursService_GetActiveTour_Handler,
		},
		{
			MethodName: "HasTourExecution",
			Handler:    _ToursService_HasTourExecution_Handler,
		},
		{
			MethodName: "CheckTourCompletion",
			Handler:    _ToursService_CheckTourCompletion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tours/tours-service.proto",
}
