// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: tours/tours-service.proto

package tours

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TourStatus int32

const (
	TourStatus_TOUR_STATUS_UNSPECIFIED TourStatus = 0
	TourStatus_DRAFT                   TourStatus = 1
	TourStatus_PENDING_PUBLISH         TourStatus = 2
	TourStatus_PUBLISHED               TourStatus = 3
	TourStatus_ARCHIVED                TourStatus = 4
)

// Enum value maps for TourStatus.
var (
	TourStatus_name = map[int32]string{
		0: "TOUR_STATUS_UNSPECIFIED",
		1: "DRAFT",
		2: "PENDING_PUBLISH",
		3: "PUBLISHED",
		4: "ARCHIVED",
	}
	TourStatus_value = map[string]int32{
		"TOUR_STATUS_UNSPECIFIED": 0,
		"DRAFT":                   1,
		"PENDING_PUBLISH":         2,
		"PUBLISHED":               3,
		"ARCHIVED":                4,
	}
)

func (x TourStatus) Enum() *TourStatus {
	p := new(TourStatus)
	*p = x
	return p
}

func (x TourStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tours_tours_service_proto_enumTypes[0].Descriptor()
}

func (TourStatus) Type() protoreflect.EnumType {
	return &file_tours_tours_service_proto_enumTypes[0]
}

func (x TourStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourStatus.Descriptor instead.
func (TourStatus) EnumDescriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{0}
}

type TransportType int32

const (
	TransportType_TRANSPORT_TYPE_UNSPECIFIED TransportType = 0
	TransportType_WALKING                    TransportType = 1
	TransportType_BIKE                       TransportType = 2
	TransportType_CAR                        TransportType = 3
)

// Enum value maps for TransportType.
var (
	TransportType_name = map[int32]string{
		0: "TRANSPORT_TYPE_UNSPECIFIED",
		1: "WALKING",
		2: "BIKE",
		3: "CAR",
	}
	TransportType_value = map[string]int32{
		"TRANSPORT_TYPE_UNSPECIFIED": 0,
		"WALKING":                    1,
		"BIKE":                       2,
		"CAR":                        3,
	}
)

func (x TransportType) Enum() *TransportType {
	p := new(TransportType)
	*p = x
	return p
}

func (x TransportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportType) Descriptor() protoreflect.EnumDescriptor {
	return file_tours_tours_service_proto_enumTypes[1].Descriptor()
}

func (TransportType) Type() protoreflect.EnumType {
	return &file_tours_tours_service_proto_enumTypes[1]
}

func (x TransportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportType.Descriptor instead.
func (TransportType) EnumDescriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{1}
}

// Zahtev je prazan
type GetPublishedToursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedToursRequest) Reset() {
	*x = GetPublishedToursRequest{}
	mi := &file_tours_tours_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedToursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedToursRequest) ProtoMessage() {}

func (x *GetPublishedToursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedToursRequest.ProtoReflect.Descriptor instead.
func (*GetPublishedToursRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{0}
}

// Odgovor sadrži listu tura
type GetPublishedToursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*PublishedTour       `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedToursResponse) Reset() {
	*x = GetPublishedToursResponse{}
	mi := &file_tours_tours_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedToursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedToursResponse) ProtoMessage() {}

func (x *GetPublishedToursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedToursResponse.ProtoReflect.Descriptor instead.
func (*GetPublishedToursResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetPublishedToursResponse) GetTours() []*PublishedTour {
	if x != nil {
		return x.Tours
	}
	return nil
}

// Poruka koja sadrži sve što frontend očekuje
type PublishedTour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Length        float64                `protobuf:"fixed64,5,opt,name=length,proto3" json:"length,omitempty"`
	StartTime     string                 `protobuf:"bytes,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	KeyPoints     []*KeyPoint            `protobuf:"bytes,7,rep,name=keyPoints,proto3" json:"keyPoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishedTour) Reset() {
	*x = PublishedTour{}
	mi := &file_tours_tours_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishedTour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishedTour) ProtoMessage() {}

func (x *PublishedTour) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishedTour.ProtoReflect.Descriptor instead.
func (*PublishedTour) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{2}
}

func (x *PublishedTour) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublishedTour) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublishedTour) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PublishedTour) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PublishedTour) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *PublishedTour) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *PublishedTour) GetKeyPoints() []*KeyPoint {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

// Zahtev za kreiranje ture
type CreateTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	AuthorId      string                 `protobuf:"bytes,5,opt,name=authorId,proto3" json:"authorId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTourRequest) Reset() {
	*x = CreateTourRequest{}
	mi := &file_tours_tours_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourRequest) ProtoMessage() {}

func (x *CreateTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourRequest.ProtoReflect.Descriptor instead.
func (*CreateTourRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTourRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTourRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTourRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *CreateTourRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateTourRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

// Odgovor sa kreiranom turom
type TourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        TourStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=TourStatus" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	AuthorId      string                 `protobuf:"bytes,8,opt,name=authorId,proto3" json:"authorId,omitempty"`
	KeyPoints     []*KeyPoint            `protobuf:"bytes,9,rep,name=keyPoints,proto3" json:"keyPoints,omitempty"`
	Durations     []*Duration            `protobuf:"bytes,10,rep,name=durations,proto3" json:"durations,omitempty"`
	Distance      float64                `protobuf:"fixed64,11,opt,name=distance,proto3" json:"distance,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=publishedAt,proto3" json:"publishedAt,omitempty"`
	ArchivedAt    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=archivedAt,proto3" json:"archivedAt,omitempty"`
	AverageRating float64                `protobuf:"fixed64,14,opt,name=averageRating,proto3" json:"averageRating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourResponse) Reset() {
	*x = TourResponse{}
	mi := &file_tours_tours_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourResponse) ProtoMessage() {}

func (x *TourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourResponse.ProtoReflect.Descriptor instead.
func (*TourResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{4}
}

func (x *TourResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TourResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TourResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TourResponse) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *TourResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TourResponse) GetStatus() TourStatus {
	if x != nil {
		return x.Status
	}
	return TourStatus_TOUR_STATUS_UNSPECIFIED
}

func (x *TourResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TourResponse) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *TourResponse) GetKeyPoints() []*KeyPoint {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

func (x *TourResponse) GetDurations() []*Duration {
	if x != nil {
		return x.Durations
	}
	return nil
}

func (x *TourResponse) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *TourResponse) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *TourResponse) GetArchivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchivedAt
	}
	return nil
}

func (x *TourResponse) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

type Duration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          TransportType          `protobuf:"varint,1,opt,name=mode,proto3,enum=TransportType" json:"mode,omitempty"`
	Minutes       int32                  `protobuf:"varint,2,opt,name=minutes,proto3" json:"minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Duration) Reset() {
	*x = Duration{}
	mi := &file_tours_tours_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duration) ProtoMessage() {}

func (x *Duration) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duration.ProtoReflect.Descriptor instead.
func (*Duration) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{5}
}

func (x *Duration) GetMode() TransportType {
	if x != nil {
		return x.Mode
	}
	return TransportType_TRANSPORT_TYPE_UNSPECIFIED
}

func (x *Duration) GetMinutes() int32 {
	if x != nil {
		return x.Minutes
	}
	return 0
}

// Zahtev za listu tura autora
type GetAuthorToursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=authorId,proto3" json:"authorId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorToursRequest) Reset() {
	*x = GetAuthorToursRequest{}
	mi := &file_tours_tours_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorToursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorToursRequest) ProtoMessage() {}

func (x *GetAuthorToursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorToursRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorToursRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetAuthorToursRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

// Odgovor sa listom tura
type GetAuthorToursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*TourResponse        `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorToursResponse) Reset() {
	*x = GetAuthorToursResponse{}
	mi := &file_tours_tours_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorToursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorToursResponse) ProtoMessage() {}

func (x *GetAuthorToursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorToursResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorToursResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetAuthorToursResponse) GetTours() []*TourResponse {
	if x != nil {
		return x.Tours
	}
	return nil
}

type GetTourByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourByIdRequest) Reset() {
	*x = GetTourByIdRequest{}
	mi := &file_tours_tours_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourByIdRequest) ProtoMessage() {}

func (x *GetTourByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTourByIdRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetTourByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateTourStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	NewStatus     TourStatus             `protobuf:"varint,3,opt,name=newStatus,proto3,enum=TourStatus" json:"newStatus,omitempty"` // Publish ili Archive
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTourStatusRequest) Reset() {
	*x = UpdateTourStatusRequest{}
	mi := &file_tours_tours_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTourStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTourStatusRequest) ProtoMessage() {}

func (x *UpdateTourStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTourStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTourStatusRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTourStatusRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *UpdateTourStatusRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *UpdateTourStatusRequest) GetNewStatus() TourStatus {
	if x != nil {
		return x.NewStatus
	}
	return TourStatus_TOUR_STATUS_UNSPECIFIED
}

type UpdateTourStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	Status        TourStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=TourStatus" json:"status,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTourStatusResponse) Reset() {
	*x = UpdateTourStatusResponse{}
	mi := &file_tours_tours_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTourStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTourStatusResponse) ProtoMessage() {}

func (x *UpdateTourStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTourStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateTourStatusResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateTourStatusResponse) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *UpdateTourStatusResponse) GetStatus() TourStatus {
	if x != nil {
		return x.Status
	}
	return TourStatus_TOUR_STATUS_UNSPECIFIED
}

func (x *UpdateTourStatusResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ----------------- KLJUČNE TAČKE -----------------
type KeyPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	ImageURL      string                 `protobuf:"bytes,6,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	Order         int32                  `protobuf:"varint,7,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPoint) Reset() {
	*x = KeyPoint{}
	mi := &file_tours_tours_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPoint) ProtoMessage() {}

func (x *KeyPoint) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPoint.ProtoReflect.Descriptor instead.
func (*KeyPoint) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{11}
}

func (x *KeyPoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeyPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyPoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KeyPoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *KeyPoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *KeyPoint) GetImageURL() string {
	if x != nil {
		return x.ImageURL
	}
	return ""
}

func (x *KeyPoint) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type AddKeyPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	Point         *KeyPoint              `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddKeyPointRequest) Reset() {
	*x = AddKeyPointRequest{}
	mi := &file_tours_tours_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddKeyPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKeyPointRequest) ProtoMessage() {}

func (x *AddKeyPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKeyPointRequest.ProtoReflect.Descriptor instead.
func (*AddKeyPointRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{12}
}

func (x *AddKeyPointRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *AddKeyPointRequest) GetPoint() *KeyPoint {
	if x != nil {
		return x.Point
	}
	return nil
}

type KeyPointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	ImageURL      string                 `protobuf:"bytes,6,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	Order         int32                  `protobuf:"varint,7,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPointResponse) Reset() {
	*x = KeyPointResponse{}
	mi := &file_tours_tours_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPointResponse) ProtoMessage() {}

func (x *KeyPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPointResponse.ProtoReflect.Descriptor instead.
func (*KeyPointResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{13}
}

func (x *KeyPointResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeyPointResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyPointResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KeyPointResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *KeyPointResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *KeyPointResponse) GetImageURL() string {
	if x != nil {
		return x.ImageURL
	}
	return ""
}

func (x *KeyPointResponse) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type UpdateKeyPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	KeyPoint      *KeyPoint              `protobuf:"bytes,2,opt,name=keyPoint,proto3" json:"keyPoint,omitempty"`
	ImageURL      string                 `protobuf:"bytes,3,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKeyPointRequest) Reset() {
	*x = UpdateKeyPointRequest{}
	mi := &file_tours_tours_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKeyPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKeyPointRequest) ProtoMessage() {}

func (x *UpdateKeyPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKeyPointRequest.ProtoReflect.Descriptor instead.
func (*UpdateKeyPointRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateKeyPointRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *UpdateKeyPointRequest) GetKeyPoint() *KeyPoint {
	if x != nil {
		return x.KeyPoint
	}
	return nil
}

func (x *UpdateKeyPointRequest) GetImageURL() string {
	if x != nil {
		return x.ImageURL
	}
	return ""
}

type DeleteKeyPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	KeypointId    string                 `protobuf:"bytes,2,opt,name=keypointId,proto3" json:"keypointId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyPointRequest) Reset() {
	*x = DeleteKeyPointRequest{}
	mi := &file_tours_tours_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyPointRequest) ProtoMessage() {}

func (x *DeleteKeyPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyPointRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeyPointRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteKeyPointRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *DeleteKeyPointRequest) GetKeypointId() string {
	if x != nil {
		return x.KeypointId
	}
	return ""
}

type DeleteKeyPointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyPointResponse) Reset() {
	*x = DeleteKeyPointResponse{}
	mi := &file_tours_tours_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyPointResponse) ProtoMessage() {}

func (x *DeleteKeyPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyPointResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeyPointResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteKeyPointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Zahtev može biti prazan
type GetAllToursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllToursRequest) Reset() {
	*x = GetAllToursRequest{}
	mi := &file_tours_tours_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllToursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllToursRequest) ProtoMessage() {}

func (x *GetAllToursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllToursRequest.ProtoReflect.Descriptor instead.
func (*GetAllToursRequest) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{17}
}

// Odgovor sadrži listu svih tura
type GetAllToursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*PublishedTour       `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllToursResponse) Reset() {
	*x = GetAllToursResponse{}
	mi := &file_tours_tours_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllToursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllToursResponse) ProtoMessage() {}

func (x *GetAllToursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tours_tours_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllToursResponse.ProtoReflect.Descriptor instead.
func (*GetAllToursResponse) Descriptor() ([]byte, []int) {
	return file_tours_tours_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetAllToursResponse) GetTours() []*PublishedTour {
	if x != nil {
		return x.Tours
	}
	return nil
}

var File_tours_tours_service_proto protoreflect.FileDescriptor

const file_tours_tours_service_proto_rawDesc = "" +
	"\n" +
	"\x19tours/tours-service.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1a\n" +
	"\x18GetPublishedToursRequest\"A\n" +
	"\x19GetPublishedToursResponse\x12$\n" +
	"\x05tours\x18\x01 \x03(\v2\x0e.PublishedTourR\x05tours\"\xca\x01\n" +
	"\rPublishedTour\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06length\x18\x05 \x01(\x01R\x06length\x12\x1c\n" +
	"\tstartTime\x18\x06 \x01(\tR\tstartTime\x12'\n" +
	"\tkeyPoints\x18\a \x03(\v2\t.KeyPointR\tkeyPoints\"\x99\x01\n" +
	"\x11CreateTourRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1a\n" +
	"\bauthorId\x18\x05 \x01(\tR\bauthorId\"\xed\x03\n" +
	"\fTourResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12#\n" +
	"\x06status\x18\x06 \x01(\x0e2\v.TourStatusR\x06status\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x1a\n" +
	"\bauthorId\x18\b \x01(\tR\bauthorId\x12'\n" +
	"\tkeyPoints\x18\t \x03(\v2\t.KeyPointR\tkeyPoints\x12'\n" +
	"\tdurations\x18\n" +
	" \x03(\v2\t.DurationR\tdurations\x12\x1a\n" +
	"\bdistance\x18\v \x01(\x01R\bdistance\x12<\n" +
	"\vpublishedAt\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12:\n" +
	"\n" +
	"archivedAt\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"archivedAt\x12$\n" +
	"\raverageRating\x18\x0e \x01(\x01R\raverageRating\"H\n" +
	"\bDuration\x12\"\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x0e.TransportTypeR\x04mode\x12\x18\n" +
	"\aminutes\x18\x02 \x01(\x05R\aminutes\"3\n" +
	"\x15GetAuthorToursRequest\x12\x1a\n" +
	"\bauthorId\x18\x01 \x01(\tR\bauthorId\"=\n" +
	"\x16GetAuthorToursResponse\x12#\n" +
	"\x05tours\x18\x01 \x03(\v2\r.TourResponseR\x05tours\"$\n" +
	"\x12GetTourByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"x\n" +
	"\x17UpdateTourStatusRequest\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\tR\x06tourId\x12\x1a\n" +
	"\bauthorId\x18\x02 \x01(\tR\bauthorId\x12)\n" +
	"\tnewStatus\x18\x03 \x01(\x0e2\v.TourStatusR\tnewStatus\"\x91\x01\n" +
	"\x18UpdateTourStatusResponse\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\tR\x06tourId\x12#\n" +
	"\x06status\x18\x02 \x01(\x0e2\v.TourStatusR\x06status\x128\n" +
	"\tupdatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xbc\x01\n" +
	"\bKeyPoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\bimageURL\x18\x06 \x01(\tR\bimageURL\x12\x14\n" +
	"\x05order\x18\a \x01(\x05R\x05order\"M\n" +
	"\x12AddKeyPointRequest\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\tR\x06tourId\x12\x1f\n" +
	"\x05point\x18\x02 \x01(\v2\t.KeyPointR\x05point\"\xc4\x01\n" +
	"\x10KeyPointResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\bimageURL\x18\x06 \x01(\tR\bimageURL\x12\x14\n" +
	"\x05order\x18\a \x01(\x05R\x05order\"r\n" +
	"\x15UpdateKeyPointRequest\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\tR\x06tourId\x12%\n" +
	"\bkeyPoint\x18\x02 \x01(\v2\t.KeyPointR\bkeyPoint\x12\x1a\n" +
	"\bimageURL\x18\x03 \x01(\tR\bimageURL\"O\n" +
	"\x15DeleteKeyPointRequest\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\tR\x06tourId\x12\x1e\n" +
	"\n" +
	"keypointId\x18\x02 \x01(\tR\n" +
	"keypointId\"2\n" +
	"\x16DeleteKeyPointResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x14\n" +
	"\x12GetAllToursRequest\";\n" +
	"\x13GetAllToursResponse\x12$\n" +
	"\x05tours\x18\x01 \x03(\v2\x0e.PublishedTourR\x05tours*f\n" +
	"\n" +
	"TourStatus\x12\x1b\n" +
	"\x17TOUR_STATUS_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05DRAFT\x10\x01\x12\x13\n" +
	"\x0fPENDING_PUBLISH\x10\x02\x12\r\n" +
	"\tPUBLISHED\x10\x03\x12\f\n" +
	"\bARCHIVED\x10\x04*O\n" +
	"\rTransportType\x12\x1e\n" +
	"\x1aTRANSPORT_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aWALKING\x10\x01\x12\b\n" +
	"\x04BIKE\x10\x02\x12\a\n" +
	"\x03CAR\x10\x032\xf1\x06\n" +
	"\fToursService\x12N\n" +
	"\n" +
	"CreateTour\x12\x12.CreateTourRequest\x1a\r.TourResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/tours/create-tour\x12\\\n" +
	"\x0eGetAuthorTours\x12\x16.GetAuthorToursRequest\x1a\x17.GetAuthorToursResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/tours/{authorId}\x12K\n" +
	"\vGetTourById\x12\x13.GetTourByIdRequest\x1a\r.TourResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/tours/tour/{id}\x12Z\n" +
	"\vAddKeyPoint\x12\x13.AddKeyPointRequest\x1a\x11.KeyPointResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/tours/add-keypoint-grpc\x12l\n" +
	"\x0eUpdateKeyPoint\x12\x16.UpdateKeyPointRequest\x1a\x11.KeyPointResponse\"/\x82\xd3\xe4\x93\x02):\x01*\x1a$/tours/tour/{tourId}/update-keypoint\x12u\n" +
	"\x0eDeleteKeyPoint\x12\x16.DeleteKeyPointRequest\x1a\x17.DeleteKeyPointResponse\"2\x82\xd3\xe4\x93\x02,**/tours/tour/{tourId}/keypoint/{keypointId}\x12d\n" +
	"\x11GetPublishedTours\x12\x19.GetPublishedToursRequest\x1a\x1a.GetPublishedToursResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/tours/published\x12L\n" +
	"\vGetAllTours\x12\x13.GetAllToursRequest\x1a\x14.GetAllToursResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/tours/all\x12q\n" +
	"\x10UpdateTourStatus\x12\x18.UpdateTourStatusRequest\x1a\x19.UpdateTourStatusResponse\"(\x82\xd3\xe4\x93\x02\":\x01*2\x1d/tours/{tourId}/update-statusB\rZ\vproto/toursb\x06proto3"

var (
	file_tours_tours_service_proto_rawDescOnce sync.Once
	file_tours_tours_service_proto_rawDescData []byte
)

func file_tours_tours_service_proto_rawDescGZIP() []byte {
	file_tours_tours_service_proto_rawDescOnce.Do(func() {
		file_tours_tours_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tours_tours_service_proto_rawDesc), len(file_tours_tours_service_proto_rawDesc)))
	})
	return file_tours_tours_service_proto_rawDescData
}

var file_tours_tours_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tours_tours_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_tours_tours_service_proto_goTypes = []any{
	(TourStatus)(0),                   // 0: TourStatus
	(TransportType)(0),                // 1: TransportType
	(*GetPublishedToursRequest)(nil),  // 2: GetPublishedToursRequest
	(*GetPublishedToursResponse)(nil), // 3: GetPublishedToursResponse
	(*PublishedTour)(nil),             // 4: PublishedTour
	(*CreateTourRequest)(nil),         // 5: CreateTourRequest
	(*TourResponse)(nil),              // 6: TourResponse
	(*Duration)(nil),                  // 7: Duration
	(*GetAuthorToursRequest)(nil),     // 8: GetAuthorToursRequest
	(*GetAuthorToursResponse)(nil),    // 9: GetAuthorToursResponse
	(*GetTourByIdRequest)(nil),        // 10: GetTourByIdRequest
	(*UpdateTourStatusRequest)(nil),   // 11: UpdateTourStatusRequest
	(*UpdateTourStatusResponse)(nil),  // 12: UpdateTourStatusResponse
	(*KeyPoint)(nil),                  // 13: KeyPoint
	(*AddKeyPointRequest)(nil),        // 14: AddKeyPointRequest
	(*KeyPointResponse)(nil),          // 15: KeyPointResponse
	(*UpdateKeyPointRequest)(nil),     // 16: UpdateKeyPointRequest
	(*DeleteKeyPointRequest)(nil),     // 17: DeleteKeyPointRequest
	(*DeleteKeyPointResponse)(nil),    // 18: DeleteKeyPointResponse
	(*GetAllToursRequest)(nil),        // 19: GetAllToursRequest
	(*GetAllToursResponse)(nil),       // 20: GetAllToursResponse
	(*timestamppb.Timestamp)(nil),     // 21: google.protobuf.Timestamp
}
var file_tours_tours_service_proto_depIdxs = []int32{
	4,  // 0: GetPublishedToursResponse.tours:type_name -> PublishedTour
	13, // 1: PublishedTour.keyPoints:type_name -> KeyPoint
	0,  // 2: TourResponse.status:type_name -> TourStatus
	13, // 3: TourResponse.keyPoints:type_name -> KeyPoint
	7,  // 4: TourResponse.durations:type_name -> Duration
	21, // 5: TourResponse.publishedAt:type_name -> google.protobuf.Timestamp
	21, // 6: TourResponse.archivedAt:type_name -> google.protobuf.Timestamp
	1,  // 7: Duration.mode:type_name -> TransportType
	6,  // 8: GetAuthorToursResponse.tours:type_name -> TourResponse
	0,  // 9: UpdateTourStatusRequest.newStatus:type_name -> TourStatus
	0,  // 10: UpdateTourStatusResponse.status:type_name -> TourStatus
	21, // 11: UpdateTourStatusResponse.updatedAt:type_name -> google.protobuf.Timestamp
	13, // 12: AddKeyPointRequest.point:type_name -> KeyPoint
	13, // 13: UpdateKeyPointRequest.keyPoint:type_name -> KeyPoint
	4,  // 14: GetAllToursResponse.tours:type_name -> PublishedTour
	5,  // 15: ToursService.CreateTour:input_type -> CreateTourRequest
	8,  // 16: ToursService.GetAuthorTours:input_type -> GetAuthorToursRequest
	10, // 17: ToursService.GetTourById:input_type -> GetTourByIdRequest
	14, // 18: ToursService.AddKeyPoint:input_type -> AddKeyPointRequest
	16, // 19: ToursService.UpdateKeyPoint:input_type -> UpdateKeyPointRequest
	17, // 20: ToursService.DeleteKeyPoint:input_type -> DeleteKeyPointRequest
	2,  // 21: ToursService.GetPublishedTours:input_type -> GetPublishedToursRequest
	19, // 22: ToursService.GetAllTours:input_type -> GetAllToursRequest
	11, // 23: ToursService.UpdateTourStatus:input_type -> UpdateTourStatusRequest
	6,  // 24: ToursService.CreateTour:output_type -> TourResponse
	9,  // 25: ToursService.GetAuthorTours:output_type -> GetAuthorToursResponse
	6,  // 26: ToursService.GetTourById:output_type -> TourResponse
	15, // 27: ToursService.AddKeyPoint:output_type -> KeyPointResponse
	15, // 28: ToursService.UpdateKeyPoint:output_type -> KeyPointResponse
	18, // 29: ToursService.DeleteKeyPoint:output_type -> DeleteKeyPointResponse
	3,  // 30: ToursService.GetPublishedTours:output_type -> GetPublishedToursResponse
	20, // 31: ToursService.GetAllTours:output_type -> GetAllToursResponse
	12, // 32: ToursService.UpdateTourStatus:output_type -> UpdateTourStatusResponse
	24, // [24:33] is the sub-list for method output_type
	15, // [15:24] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_tours_tours_service_proto_init() }
func file_tours_tours_service_proto_init() {
	if File_tours_tours_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tours_tours_service_proto_rawDesc), len(file_tours_tours_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tours_tours_service_proto_goTypes,
		DependencyIndexes: file_tours_tours_service_proto_depIdxs,
		EnumInfos:         file_tours_tours_service_proto_enumTypes,
		MessageInfos:      file_tours_tours_service_proto_msgTypes,
	}.Build()
	File_tours_tours_service_proto = out.File
	file_tours_tours_service_proto_goTypes = nil
	file_tours_tours_service_proto_depIdxs = nil
}
