// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: position/position-service.proto

package position

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=touristId,proto3" json:"touristId,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordPositionRequest) Reset() {
	*x = RecordPositionRequest{}
	mi := &file_position_position_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPositionRequest) ProtoMessage() {}

func (x *RecordPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_position_position_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPositionRequest.ProtoReflect.Descriptor instead.
func (*RecordPositionRequest) Descriptor() ([]byte, []int) {
	return file_position_position_service_proto_rawDescGZIP(), []int{0}
}

func (x *RecordPositionRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *RecordPositionRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RecordPositionRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type GetCurrentPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=touristId,proto3" json:"touristId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentPositionRequest) Reset() {
	*x = GetCurrentPositionRequest{}
	mi := &file_position_position_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentPositionRequest) ProtoMessage() {}

func (x *GetCurrentPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_position_position_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentPositionRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentPositionRequest) Descriptor() ([]byte, []int) {
	return file_position_position_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentPositionRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

type PositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=touristId,proto3" json:"touristId,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionResponse) Reset() {
	*x = PositionResponse{}
	mi := &file_position_position_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionResponse) ProtoMessage() {}

func (x *PositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_position_position_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionResponse.ProtoReflect.Descriptor instead.
func (*PositionResponse) Descriptor() ([]byte, []int) {
	return file_position_position_service_proto_rawDescGZIP(), []int{2}
}

func (x *PositionResponse) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *PositionResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *PositionResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *PositionResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_position_position_service_proto protoreflect.FileDescriptor

const file_position_position_service_proto_rawDesc = "" +
	"\n" +
	"\x1fposition/position-service.proto\x1a\x1cgoogle/api/annotations.proto\"o\n" +
	"\x15RecordPositionRequest\x12\x1c\n" +
	"\ttouristId\x18\x01 \x01(\tR\ttouristId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"9\n" +
	"\x19GetCurrentPositionRequest\x12\x1c\n" +
	"\ttouristId\x18\x01 \x01(\tR\ttouristId\"\x88\x01\n" +
	"\x10PositionResponse\x12\x1c\n" +
	"\ttouristId\x18\x01 \x01(\tR\ttouristId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1c\n" +
	"\tupdatedAt\x18\x04 \x01(\x03R\tupdatedAt2\xc8\x01\n" +
	"\x0fPositionService\x12Q\n" +
	"\x0eRecordPosition\x12\x16.RecordPositionRequest\x1a\x11.PositionResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/position\x12b\n" +
	"\x12GetCurrentPosition\x12\x1a.GetCurrentPositionRequest\x1a\x11.PositionResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/position/{touristId}B\x10Z\x0eproto/positionb\x06proto3"

var (
	file_position_position_service_proto_rawDescOnce sync.Once
	file_position_position_service_proto_rawDescData []byte
)

func file_position_position_service_proto_rawDescGZIP() []byte {
	file_position_position_service_proto_rawDescOnce.Do(func() {
		file_position_position_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_position_position_service_proto_rawDesc), len(file_position_position_service_proto_rawDesc)))
	})
	return file_position_position_service_proto_rawDescData
}

var file_position_position_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_position_position_service_proto_goTypes = []any{
	(*RecordPositionRequest)(nil),     // 0: RecordPositionRequest
	(*GetCurrentPositionRequest)(nil), // 1: GetCurrentPositionRequest
	(*PositionResponse)(nil),          // 2: PositionResponse
}
var file_position_position_service_proto_depIdxs = []int32{
	0, // 0: PositionService.RecordPosition:input_type -> RecordPositionRequest
	1, // 1: PositionService.GetCurrentPosition:input_type -> GetCurrentPositionRequest
	2, // 2: PositionService.RecordPosition:output_type -> PositionResponse
	2, // 3: PositionService.GetCurrentPosition:output_type -> PositionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_position_position_service_proto_init() }
func file_position_position_service_proto_init() {
	if File_position_position_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_position_position_service_proto_rawDesc), len(file_position_position_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_position_position_service_proto_goTypes,
		DependencyIndexes: file_position_position_service_proto_depIdxs,
		MessageInfos:      file_position_position_service_proto_msgTypes,
	}.Build()
	File_position_position_service_proto = out.File
	file_position_position_service_proto_goTypes = nil
	file_position_position_service_proto_depIdxs = nil
}
