// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: follower/follower.proto

package follower

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolloweeId    string                 `protobuf:"bytes,1,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"` // iz path-a
	FollowerId    string                 `protobuf:"bytes,2,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"` // gateway ubaci iz JWT-a (ne iz fronta)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_follower_follower_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follower_follower_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_follower_follower_proto_rawDescGZIP(), []int{0}
}

func (x *FollowRequest) GetFolloweeId() string {
	if x != nil {
		return x.FolloweeId
	}
	return ""
}

func (x *FollowRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

type UnfollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolloweeId    string                 `protobuf:"bytes,1,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"` // iz path-a
	FollowerId    string                 `protobuf:"bytes,2,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"` // iz JWT-a
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowRequest) Reset() {
	*x = UnfollowRequest{}
	mi := &file_follower_follower_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowRequest) ProtoMessage() {}

func (x *UnfollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follower_follower_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowRequest.ProtoReflect.Descriptor instead.
func (*UnfollowRequest) Descriptor() ([]byte, []int) {
	return file_follower_follower_proto_rawDescGZIP(), []int{1}
}

func (x *UnfollowRequest) GetFolloweeId() string {
	if x != nil {
		return x.FolloweeId
	}
	return ""
}

func (x *UnfollowRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

type GetRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // gateway popuni iz JWT-a
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                // iz query-ja (?limit=)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsRequest) Reset() {
	*x = GetRecommendationsRequest{}
	mi := &file_follower_follower_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsRequest) ProtoMessage() {}

func (x *GetRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follower_follower_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_follower_follower_proto_rawDescGZIP(), []int{2}
}

func (x *GetRecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRecommendationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Recommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mutual        int64                  `protobuf:"varint,2,opt,name=mutual,proto3" json:"mutual,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	mi := &file_follower_follower_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_follower_follower_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_follower_follower_proto_rawDescGZIP(), []int{3}
}

func (x *Recommendation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Recommendation) GetMutual() int64 {
	if x != nil {
		return x.Mutual
	}
	return 0
}

type GetRecommendationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Recommendation      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsResponse) Reset() {
	*x = GetRecommendationsResponse{}
	mi := &file_follower_follower_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsResponse) ProtoMessage() {}

func (x *GetRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follower_follower_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_follower_follower_proto_rawDescGZIP(), []int{4}
}

func (x *GetRecommendationsResponse) GetItems() []*Recommendation {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetFolloweesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // gateway može da ga popuni iz JWT-a
	Skip          int32                  `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`                  // iz query-ja
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                // iz query-ja
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFolloweesRequest) Reset() {
	*x = GetFolloweesRequest{}
	mi := &file_follower_follower_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFolloweesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFolloweesRequest) ProtoMessage() {}

func (x *GetFolloweesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_follower_follower_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFolloweesRequest.ProtoReflect.Descriptor instead.
func (*GetFolloweesRequest) Descriptor() ([]byte, []int) {
	return file_follower_follower_proto_rawDescGZIP(), []int{5}
}

func (x *GetFolloweesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFolloweesRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *GetFolloweesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetFolloweesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFolloweesResponse) Reset() {
	*x = GetFolloweesResponse{}
	mi := &file_follower_follower_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFolloweesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFolloweesResponse) ProtoMessage() {}

func (x *GetFolloweesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_follower_follower_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFolloweesResponse.ProtoReflect.Descriptor instead.
func (*GetFolloweesResponse) Descriptor() ([]byte, []int) {
	return file_follower_follower_proto_rawDescGZIP(), []int{6}
}

func (x *GetFolloweesResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_follower_follower_proto protoreflect.FileDescriptor

const file_follower_follower_proto_rawDesc = "" +
	"\n" +
	"\x17follower/follower.proto\x12\bfollower\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"Q\n" +
	"\rFollowRequest\x12\x1f\n" +
	"\vfollowee_id\x18\x01 \x01(\tR\n" +
	"followeeId\x12\x1f\n" +
	"\vfollower_id\x18\x02 \x01(\tR\n" +
	"followerId\"S\n" +
	"\x0fUnfollowRequest\x12\x1f\n" +
	"\vfollowee_id\x18\x01 \x01(\tR\n" +
	"followeeId\x12\x1f\n" +
	"\vfollower_id\x18\x02 \x01(\tR\n" +
	"followerId\"J\n" +
	"\x19GetRecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"A\n" +
	"\x0eRecommendation\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06mutual\x18\x02 \x01(\x03R\x06mutual\"L\n" +
	"\x1aGetRecommendationsResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.follower.RecommendationR\x05items\"X\n" +
	"\x13GetFolloweesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"1\n" +
	"\x14GetFolloweesResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds2\xd6\x03\n" +
	"\x0fFollowerService\x12e\n" +
	"\x06Follow\x12\x17.follower.FollowRequest\x1a\x16.google.protobuf.Empty\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/followers/{followee_id}:follow\x12_\n" +
	"\bUnfollow\x12\x19.follower.UnfollowRequest\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a*\x18/followers/{followee_id}\x12\x83\x01\n" +
	"\x12GetRecommendations\x12#.follower.GetRecommendationsRequest\x1a$.follower.GetRecommendationsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/followers/recommendations\x12u\n" +
	"\fGetFollowees\x12\x1d.follower.GetFolloweesRequest\x1a\x1e.follower.GetFolloweesResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/followers/{user_id}/followeesB\x10Z\x0eproto/followerb\x06proto3"

var (
	file_follower_follower_proto_rawDescOnce sync.Once
	file_follower_follower_proto_rawDescData []byte
)

func file_follower_follower_proto_rawDescGZIP() []byte {
	file_follower_follower_proto_rawDescOnce.Do(func() {
		file_follower_follower_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_follower_follower_proto_rawDesc), len(file_follower_follower_proto_rawDesc)))
	})
	return file_follower_follower_proto_rawDescData
}

var file_follower_follower_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_follower_follower_proto_goTypes = []any{
	(*FollowRequest)(nil),              // 0: follower.FollowRequest
	(*UnfollowRequest)(nil),            // 1: follower.UnfollowRequest
	(*GetRecommendationsRequest)(nil),  // 2: follower.GetRecommendationsRequest
	(*Recommendation)(nil),             // 3: follower.Recommendation
	(*GetRecommendationsResponse)(nil), // 4: follower.GetRecommendationsResponse
	(*GetFolloweesRequest)(nil),        // 5: follower.GetFolloweesRequest
	(*GetFolloweesResponse)(nil),       // 6: follower.GetFolloweesResponse
	(*emptypb.Empty)(nil),              // 7: google.protobuf.Empty
}
var file_follower_follower_proto_depIdxs = []int32{
	3, // 0: follower.GetRecommendationsResponse.items:type_name -> follower.Recommendation
	0, // 1: follower.FollowerService.Follow:input_type -> follower.FollowRequest
	1, // 2: follower.FollowerService.Unfollow:input_type -> follower.UnfollowRequest
	2, // 3: follower.FollowerService.GetRecommendations:input_type -> follower.GetRecommendationsRequest
	5, // 4: follower.FollowerService.GetFollowees:input_type -> follower.GetFolloweesRequest
	7, // 5: follower.FollowerService.Follow:output_type -> google.protobuf.Empty
	7, // 6: follower.FollowerService.Unfollow:output_type -> google.protobuf.Empty
	4, // 7: follower.FollowerService.GetRecommendations:output_type -> follower.GetRecommendationsResponse
	6, // 8: follower.FollowerService.GetFollowees:output_type -> follower.GetFolloweesResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_follower_follower_proto_init() }
func file_follower_follower_proto_init() {
	if File_follower_follower_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_follower_follower_proto_rawDesc), len(file_follower_follower_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_follower_follower_proto_goTypes,
		DependencyIndexes: file_follower_follower_proto_depIdxs,
		MessageInfos:      file_follower_follower_proto_msgTypes,
	}.Build()
	File_follower_follower_proto = out.File
	file_follower_follower_proto_goTypes = nil
	file_follower_follower_proto_depIdxs = nil
}
